name: rocket_chat_dart
description: Similar to Rocket.Chat.Go.SDK and implement APIs according to the Rocket Chat document.
version: 0.0.39
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/rocket.chat.dart
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  enhanced_ddp: ^1.2.3
  crypto: ^2.1.5
  http: ^0.12.2
  json_annotation: ^3.1.1

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.2.7
  json_serializable: ^2.0.2
