name: rocket_chat_dart
description: n/a
version: 0.0.11
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/rocket.chat.dart
environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  ddp: ^0.0.8
  crypto: ^2.0.6
  json_serializable: ^1.4.0
  http: ^0.12.0
  json_annotation: ^1.2.0

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.0.0
